version: '1'

services:
  db:
    container_name: dbmaria
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: escola

  # web:
  #   container_name: api-rest
  #   image: api-rest
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db
  #   networks:
  #     - api-network
